/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-04-08 07:15:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menubar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1648472838000L));
    _jspx_dependants.put("jar:file:/C:/CatProject/cat/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>My Cat</title>\r\n");
      out.write("\r\n");
      out.write("<!-- ----------------------------------------------------------------------------------------- -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("header {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header h1#logo {\r\n");
      out.write("	font-size: 36pt;\r\n");
      out.write("	font-style: italic;\r\n");
      out.write("	color: navy;\r\n");
      out.write("	text-shadow: 2px 2px 2px gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header ul#menubar {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	left: 150px;\r\n");
      out.write("	top: -30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header ul#menubar li {\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 120px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	margin-right: 5px;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header ul#menubar li a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	width: 120px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	display: block;\r\n");
      out.write("	background-color: orange;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: navy;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	text-shadow: 1px1px 2px white;\r\n");
      out.write("	padding-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header ul#menubar li a:hover {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	width: 120px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	display: block;\r\n");
      out.write("	background-color: navy;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	text-shadow: 1px1px 2px navy;\r\n");
      out.write("	padding-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hr {\r\n");
      out.write("	clear: both;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("            <h1 class=\"site-heading text-center text-faded d-none d-lg-block\">\r\n");
      out.write("                <span class=\"site-heading-upper text-primary mb-3\">My Cat</span>\r\n");
      out.write("            </h1>\r\n");
      out.write("	<!-- 로그인 안 한 경우 -->\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 로그인 한 경우 : 관리자인 경우-->\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 로그인 한 경우 : 일반회원인 경우 -->\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("	body {font-size:11pt; padding:0; margin:0;}\r\n");
      out.write("	h3 {color: #85144b; font-size: 14pt;}\r\n");
      out.write("\r\n");
      out.write("	#promotionBanner {width: 100%; height: 110px; background-color:white; color: #f1f1f1; overflow: hidden;}\r\n");
      out.write("	.popContents {width: 1100px; margin: 0 auto; padding: 0; overflow: hidden; text-align: center;}\r\n");
      out.write("	.popClose {width: 1100px; marign: 0 auto; text-align: right; font-size: 9pt; padding: 0;}\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	#chkday {color: #5a5a5a;}\r\n");
      out.write("	label[for=chkday] { cursor: pointer; color: black; padding-right: 10px;}\r\n");
      out.write("\r\n");
      out.write("	.contents {width: 1100px; margin: 0 auto; height: 900px; background-color: #e0e0e0; overflow: hidden; padding: 20px;}\r\n");
      out.write("//-->\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("	//쿠키저장 함수\r\n");
      out.write("	function setCookie( name, value, expiredays ) { \r\n");
      out.write("		var todayDate = new Date(); \r\n");
      out.write("		todayDate.setDate( todayDate.getDate() + expiredays ); \r\n");
      out.write("		document.cookie = name + \"=\" + escape( value ) + \"; path=/; expires=\" + todayDate.toGMTString() + \";\" \r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		$(\"#promotionBanner .btnClose\").click(function(){\r\n");
      out.write("			//오늘만 보기 체크박스의 체크 여부를 확인 해서 체크되어 있으면 쿠키를 생성한다.\r\n");
      out.write("			if($(\"#chkday\").is(':checked')){\r\n");
      out.write("				setCookie( \"topPop\", \"done\" , 1 ); \r\n");
      out.write("				//alert(\"쿠키를 생성하였습니다.\");\r\n");
      out.write("			}\r\n");
      out.write("			//팝업창을 위로 애니메이트 시킨다. 혹은 slideUp()\r\n");
      out.write("			//$('#promotionBanner').animate({height: 0}, 500);\r\n");
      out.write("			$('#promotionBanner').slideUp(500); \r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("//-->  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Layer POPUP -->\r\n");
      out.write("<div id=\"promotionBanner\">\r\n");
      out.write("	<div class=\"popContents\">\r\n");
      out.write("		<img class=\"banner\" src=\"resources/static/img/banner2.jpg\" height=\"80\">\r\n");
      out.write("		<div class=\"popClose\">\r\n");
      out.write("		<input type=\"checkbox\" value=\"checkbox\" name=\"chkbox\" id=\"chkday\"/><label for=\"chkday\">오늘 하루 그만보기 </label> \r\n");
      out.write("        <a href=\"#none\" class=\"btnClose\"><img src=\"resources/static/img/img1.png\" alt=\"배너 닫기\" width=\"15\" />닫기</a></div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>  \r\n");
      out.write("\r\n");
      out.write("<script language=\"Javascript\">\r\n");
      out.write("	//저장된 해당 쿠키가 있으면 창을 안 띄운다 없으면 뛰운다.\r\n");
      out.write("	cookiedata = document.cookie;    \r\n");
      out.write("	if ( cookiedata.indexOf(\"topPop=done\") < 0 ){      \r\n");
      out.write("		document.all['promotionBanner'].style.display = \"block\";\r\n");
      out.write("		} \r\n");
      out.write("	else {\r\n");
      out.write("		document.all['promotionBanner'].style.display = \"none\"; \r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/common/menubar.jsp(78,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty sessionScope.loginMember }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<nav class=\"navbar navbar-expand-lg navbar-dark py-lg-4\" id=\"mainNav\">\r\n");
          out.write("			<div class=\"container\">\r\n");
          out.write("				<a class=\"navbar-brand text-uppercase fw-bold d-lg-none\"\r\n");
          out.write("					href=\"main.do\">냥덕쓰</a>\r\n");
          out.write("				<button class=\"navbar-toggler\" type=\"button\"\r\n");
          out.write("					data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
          out.write("					aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
          out.write("					aria-label=\"Toggle navigation\">\r\n");
          out.write("					<span class=\"navbar-toggler-icon\"></span>\r\n");
          out.write("				</button>\r\n");
          out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
          out.write("					<ul class=\"navbar-nav mx-auto\">\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"main.do\">메인 홈</a></li>\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/nlist.do?page=1\">공지사항</a></li>\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"famous.do\">인기고양이 정보</a></li>\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/blist.do?page=1\">게시판</a></li>\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"measure.do\">고양이 비만도 진단하기</a></li>\r\n");
          out.write("					</ul>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("		</nav>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/common/menubar.jsp(108,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty sessionScope.loginMember and sessionScope.loginMember.admin_ok eq 'Y' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<nav class=\"navbar navbar-expand-lg navbar-dark py-lg-4\" id=\"mainNav\">\r\n");
          out.write("			<div class=\"container\">\r\n");
          out.write("				<a class=\"navbar-brand text-uppercase fw-bold d-lg-none\"\r\n");
          out.write("					href=\"main.do\">냥덕쓰</a>\r\n");
          out.write("				<button class=\"navbar-toggler\" type=\"button\"\r\n");
          out.write("					data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
          out.write("					aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
          out.write("					aria-label=\"Toggle navigation\">\r\n");
          out.write("					<span class=\"navbar-toggler-icon\"></span>\r\n");
          out.write("				</button>\r\n");
          out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
          out.write("					<ul class=\"navbar-nav mx-auto\">\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"main.do\">메인 홈</a></li>\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"famous.do\">인기고양이 정보 관리</a></li>\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"mlist.do\">회원 관리</a></li>\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/nlist.do?page=1\">공지사항</a></li>\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/blist.do?page=1\">게시판</a></li>\r\n");
          out.write("					</ul>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("		</nav>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/common/menubar.jsp(138,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty sessionScope.loginMember and sessionScope.loginMember.admin_ok eq 'N'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<nav class=\"navbar navbar-expand-lg navbar-dark py-lg-4\" id=\"mainNav\">\r\n");
          out.write("			<div class=\"container\">\r\n");
          out.write("				<a class=\"navbar-brand text-uppercase fw-bold d-lg-none\"\r\n");
          out.write("					href=\"main.do\">냥덕쓰</a>\r\n");
          out.write("				<button class=\"navbar-toggler\" type=\"button\"\r\n");
          out.write("					data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
          out.write("					aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
          out.write("					aria-label=\"Toggle navigation\">\r\n");
          out.write("					<span class=\"navbar-toggler-icon\"></span>\r\n");
          out.write("				</button>\r\n");
          out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
          out.write("					<ul class=\"navbar-nav mx-auto\">\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"main.do\">메인 홈</a></li>\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/nlist.do?page=1\">공지사항</a></li>\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"famous.do\">인기고양이 정보</a></li>\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/blist.do?page=1\">게시판</a></li>\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"measure.do\">고양이 비만도 진단하기</a></li>\r\n");
          out.write("						<li class=\"nav-item px-lg-4\"><a\r\n");
          out.write("							class=\"nav-link text-uppercase\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/cmlist.do?user_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope.loginMember.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">내 고양이 관리</a></li>\r\n");
          out.write("					</ul>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("		</nav>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
